version: '3'

services:
 test-db:
    container_name: test_db_patients
    image: postgres
    ports:
      - 6543:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: patients
