name: backend CI
on: workflow_dispatch

jobs:
  test:
    name: Testing backend
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: patients
        
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@9.5
        with:
          cli: latest

      - name: Run tests
        run: clojure -M:test
  
  build_and_push:
    name: Build Docker image and push to Docker Hub
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Metadata action
        uses: docker/metadata-action@v4.1.1
        id: meta
        with:
          images: dimitri21/clojure-patient-backend

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          context: .
          file: ./docker/backend/Dockerfile