name: Test frontend
on: workflow_dispatch

jobs:
  test:
    name: Test frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Run frontend tests
        run: npm run test
