name: frontend CI
on: push

jobs:
  test:
    name: Testing frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Run frontend tests
        run: npm run test
  
  build_and_push:
    name: Build Docker image and push to Docker Hub
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Metadata action
        uses: docker/metadata-action@v4.1.1
        id: meta
        with:
          images: dimitri21/clojure-patient-frontend

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          context: .
          file: ./docker/frontend/Dockerfile